In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp- yt)
    print("Total error is :",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is :",mae)
    return mae

In [4]:
mae(y_predicted , y_true)

Total error is : 2.5
Mean absolute error is : 0.5


0.5

In [5]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [8]:
def  mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted - y_true))

In [9]:
 mae_np(y_predicted, y_true)

0.5

Implement Log Loss or Binary Cross Entropy

In [10]:
np.log([0])

C:\Users\Saurabh\AppData\Local\Temp\ipykernel_10080\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [12]:
epsilon = 1e-15

In [13]:
np.log([1e-15])

array([-34.53877639])

In [14]:
y_predicted

array([1, 1, 0, 0, 1])

In [19]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [16]:
1-epsilon

0.999999999999999

In [22]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[1e-15, 1e-15, 1e-15, 1e-15, 1e-15]

In [23]:
y_predicted_new = np.array(y_predicted_new)

In [24]:
np.log(y_predicted_new)

array([-34.53877639, -34.53877639, -34.53877639, -34.53877639,
       -34.53877639])

In [25]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.269388197455342

In [26]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))